schema_version = "1.0.0"



id = "secret_paint"
version = "1.9.12"
name = "Secret Paint"
tagline = "Select an object, select a surface, paint"
maintainer = "orencloud"

type = "add-on"


website = "https://orencloud.art/secretpaint"
support = "https://github.com/orencloud/Secret-Paint/issues"



tags = ["Modeling", "Add Curve"]

blender_version_min = "5.1.0"






license = [
  'SPDX:GPL-3.0-or-later',
]

copyright = ["2022-2024 orencloud"]





[permissions]
files = "Export objects and biomes to external blend files"